### PR TITLE
fixed spell creation and savedbc()

### PR DESCRIPTION
**Pull request by lynsky**

### CODE REVIEW

**Comment by stoneharry** [comment]
As far as I know the current release build works fine:

https://github.com/stoneharry/Spell-Editor-GUI-V2/releases/tag/v1.1

But the commits done by Grimtonz1337 broke some things. I haven't really looked at those newer versions.

Thanks for your work merged here, do you know of any other issues? I may take a look at it at some point if people actually use this tool. You mention only the English locale is currently saved? I'm sure it used to work.

**Comment by lynsky** [comment]
It didnt save at all, I just quickly made it to use the english EditBox values for saving. Probably broken with that commit you mentioned.

**Comment by stoneharry** [comment]
Okay, I am not sure where you got documentation on TextFlags but it seems incorrect.

From my analysis the last column is ALWAYS the value you document as HAS_TEXT. The other columns all relate to localisations, there are no other flag columns. Furthermore, the client doesn't actually even read the flag column for each string.

I have committed updates to the code to reflect and fix up this. Thanks for helping out.

**Comment by lynsky** [comment]
image

Well no Idea if the client reads it or not, maybe editing works for most part generally so nobody payed real attention. Im just trying to "emulate" if based on deduction and comparison with other values.

Take a loot at columns 137, 154, 171 and 180. They are followed by a value I called "text_flags" because they obviously relate to the previous text. 

Wherever THERE IS a string in the previous field, text_flag is 0xFF01FE so I assume it means "there is text", where THERE IS NO string, the value is 0xFF01FC. Only those 2 values appear.

**Comment by stoneharry** [comment]
You have hide unknown and hide zero columns enabled. What is the view with those unticked?

I have a patch ~3.3.x spell DBC file populated with every single locale:

image

The ??? fields are characters MyDBCEditor cannot render as it does not implement UTF-8 properly apparently.

Not all locales are filled because to my understanding not all are implemented (maybe internal languages?).

The flags column is not read by the client, I can confirm.

**Comment by lynsky** [comment]
image
image
image

Seems all are zero and dont affect the flags value. Well if you can confirm it, then no point wasting our time further with this :D

**Pull request merged**
